# Generated by Django 5.0.3 on 2024-03-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('INPROGRESS', 'INPROGRESS')], default='OPEN', max_length=20),
        ),
    ]
