# Generated by Django 5.0.3 on 2024-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('IN_PROGRESS', 'In Progress')], default='OPEN', max_length=20),
        ),
    ]
