name: Django CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Open Web Client Directory
        run: |
          ls -la /usr/bin/git/*
          ls -al  /home/runner/work/Lodge_Complaint_Service_Management_System/Lodge_Complaint_Service_Management_System/*

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
          pip install -r Lodge_Complaint_Service_Management_System/requirements.txt

      - name: Install coverage package
        run: pip install coverage

      - name: Run tests
        run: | 
          python Lodge_Complaint_Service_Management_System/manage.py test

      - name: Generate coverage report
        run: |
          coverage run manage.py test
          coverage report

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
